### ISSUE TITLE
One more to add

### ISSUE THREAD

**Issue by imtaurus94** [jslee02/awesome-robotics-libraries#2]
Hi,

i think TP+ should be included on your list.
https://github.com/onerobotics/tp_plus

Thanks!

**Comment by jslee02** [comment]
Thank you for the suggestion. However, I'm not convinced if TP+ fits the list. sweat: It seems that the library is for a company ([One Robotics Company](http://www.onerobotics.com/)) specific programming language. Please let me know if I'm missing something here.
