### ISSUE TITLE
Another awesome-robotics list

### ISSUE THREAD

**Issue by ahundt** [jslee02/awesome-robotics-libraries#3]
Found your list and added it to my own, which is also software focused https://github.com/ahundt/awesome-robotics.

**Comment by jslee02** [comment]
Thanks for sharing! [I also added the link to your list to my list](https://github.com/jslee02/awesome-robotics-libraries/commit/2be92144a071bbaab6f09edbe2f66a031d577742). I wish it had a different name since it's already occupied though. :sweat:

**Comment by ahundt** [comment]
yeah... a bit unfortunate. Thanks!
